### ISSUE TITLE
Scripts cannot be added to webpack.config.js using Latest version of Angular CLI

### ISSUE THREAD

**Issue by andreidiaconescu** [maximegris/angular-electron#119] opened 2018-01-27 23:00 UTC
Hello,

I tried to add boostrap 3 library to my project, that uses this starter project.
Steps done:
1. npm install bootstrap@3 jquery --save
2. edit webpack.config.js
.......................................................................
//add all external css to be added in our index.html--> like as if it's .angular-cli.json
const styles = [
  "./src/styles.scss",
  "./node_modules/bootstrap/dist/css/bootstrap.min.css"
];

//we add all our external scripts we want to load externally, like inserting in our index.html --> like as if it's .angular-cli.json
const scripts = [
    "./node_modules/jquery/dist/jquery.min.js",
    "./node_modules/bootstrap/dist/js/bootstrap.min.js"
];
 ...................................................................

3. run npm start
i get the error:

TypeError: InsertConcatAssetsWebpackPlugin is not a constructor
    at getPlugins (/home/andrei/Projects/var/electron/angular-electron-maximegris/webpack.config.js:101:18)
    at Object.<anonymous> (/home/andrei/Projects/var/electron/angular-electron-maximegris/webpack.config.js:536:14)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at requireConfig (/home/andrei/Projects/var/electron/angular-electron-maximegris/node_modules/webpack/bin/convert-argv.js:97:18)
    at /home/andrei/Projects/var/electron/angular-electron-maximegris/node_modules/webpack/bin/convert-argv.js:104:17
    at Array.forEach (<anonymous>)
    at module.exports (/home/andrei/Projects/var/electron/angular-electron-maximegris/node_modules/webpack/bin/convert-argv.js:102:15)
    at yargs.parse (/home/andrei/Projects/var/electron/angular-electron-maximegris/node_modules/webpack/bin/webpack.js:171:41)
    at Object.Yargs.self.parse (/home/andrei/Projects/var/electron/angular-electron-maximegris/node_modules/webpack/node_modules/yargs/yargs.js:533:18)
    at Object.<anonymous> (/home/andrei/Projects/var/electron/angular-electron-maximegris/node_modules/webpack/bin/webpack.js:152:7)

A bit of investigation i did that may help:
 - please check commit https://github.com/angular/angular-cli/commit/8cea8ffdc28908b325d8a56f06ff3d626efdeb8d#diff-814e1e541d11a4d19bc04e52faf2a683
where you can see that the webpack plugin InsertConcatAssetsWebpackPlugin was removed from Angular CLI.

Can you please advise on how to add Boostrap 3 to the project ?
Thank you !

**Comment by mo2menelzeiny** [comment] 2018-01-27 23:23
Yeah it's becasue the new cli version doesn't having this class, I just resolved this by replacing the `InsertConcatAssetsWebpackPlugin` with the new `ScriptsWebpackPlugin`. 

`const {BaseHrefWebpackPlugin, NamedLazyChunksWebpackPlugin, ScriptsWebpackPlugin} = require('@angular/cli/plugins/webpack');`

now in the implementation replace 
```
plugins.push(new InsertConcatAssetsWebpackPlugin([
      "scripts"
    ]));
```
with the new imported ScriptsWebpackPlugin implementation
```
plugins.push(new ScriptsWebpackPlugin({
      name: "scripts",
      sourceMap: true,
      scripts: scripts
    }));
```

**Comment by mo2menelzeiny** [comment] 2018-01-27 23:23
Duplicate of #118

**Comment by maximegris** [comment] 2018-02-15 09:07
Thanks @mo2menelzeiny for the PR 👍

**Closed by maximegris** 2018-02-15 09:07 UTC

**Comment by henrylow97** [comment] 2020-11-19 02:16
Hi, may I know whats the value for the variable "scripts" under:
`scripts: scripts`

Cuz I'm getting "scripts" of undefined error
