### ISSUE TITLE
Is it possible to run karma units tests in this repository?

### ISSUE THREAD

**Issue by rylphs** [maximegris/angular-electron#50] opened 2017-07-28 14:11 UTC
I tried to run npm test in this repository but if I have any electron import in my angular services I get the following error: 

Uncaught TypeError: fs.existsSync is not a function
  at http://127.0.0.1:9876/_karma_webpack_/vendor.bundle.js:94

Is it possible to run karma units tests in this repository?

**Comment by maximegris** [comment] 2017-08-10 10:22
I have no error with `npm run test`. What is your OS ?

**Comment by samsamm777** [comment] 2017-08-21 10:24
I'm having the same issues.

`Chrome 60.0.3112 (Linux 0.0.0) ERROR
  Uncaught TypeError: fs.existsSync is not a function
  at http://localhost:9877webpack:///~/electron/index.js:6:0 <- src/test.ts:44686
`

**Comment by BrunoDF** [comment] 2017-09-08 05:51
I'm having the same problem too.

I have searched for a reason and it seems to be a problem happening when you require 'electron'.

Apparently if you import 'electron' it doesn't happen (needs check). The problem is that I need access to some stuff from electron.remote.

Any thoughts?

**Comment by Kaffiend** [comment] 2018-01-12 05:34
Sounds like Webpacks own require is shadowing the normal require electron uses. This should of been fixed with the webpack electron renderer target though.

**Comment by lacroixdavid1** [comment] 2018-01-27 23:05
i am getting this error 

'''
SilentError: Unable to find any apps in `.angular-cli.json`.
'''

**Comment by Mokkapps** [comment] 2018-01-29 16:19
Same problem here:

`
Chrome 63.0.3239 (Mac OS X 10.13.3) ERROR
  {
    "message": "Uncaught TypeError: fs.existsSync is not a function\nat http://localhost:9876/_karma_webpack_/vendor.bundle.js:3900:8\n\nTypeError: fs.existsSync is not a function\n    at Object.<anonymous> (http://localhost:9876/_karma_webpack_/vendor.bundle.js:3900:8)\n    at Object.../../../../electron/index.js (http://localhost:9876/_karma_webpack_/vendor.bundle.js:3906:30)\n    at __webpack_require__ (http://localhost:9876/_karma_webpack_/inline.bundle.js:55:30)\n    at Object.../../../../../src/app/providers/settings.service.ts (http://localhost:9876/_karma_webpack_/main.bundle.js:228:18)\n    at __webpack_require__ (http://localhost:9876/_karma_webpack_/inline.bundle.js:55:30)\n    at Object.../../../../../src/app/providers/settings.service.spec.ts (http://localhost:9876/_karma_webpack_/main.bundle.js:187:26)\n    at __webpack_require__ (http://localhost:9876/_karma_webpack_/inline.bundle.js:55:30)\n    at webpackContext (http://localhost:9876/_karma_webpack_/main.bundle.js:11:9)\n    at Array.map (<anonymous>)\n    at Object.../../../../../src/test.ts (http://localhost:9876/_karma_webpack_/main.bundle.js:385:16)",
    "str": "Uncaught TypeError: fs.existsSync is not a function\nat http://localhost:9876/_karma_webpack_/vendor.bundle.js:3900:8\n\nTypeError: fs.existsSync is not a function\n    at Object.<anonymous> (http://localhost:9876/_karma_webpack_/vendor.bundle.js:3900:8)\n    at Object.../../../../electron/index.js (http://localhost:9876/_karma_webpack_/vendor.bundle.js:3906:30)\n    at __webpack_require__ (http://localhost:9876/_karma_webpack_/inline.bundle.js:55:30)\n    at Object.../../../../../src/app/providers/settings.service.ts (http://localhost:9876/_karma_webpack_/main.bundle.js:228:18)\n    at __webpack_require__ (http://localhost:9876/_karma_webpack_/inline.bundle.js:55:30)\n    at Object.../../../../../src/app/providers/settings.service.spec.ts (http://localhost:9876/_karma_webpack_/main.bundle.js:187:26)\n    at __webpack_require__ (http://localhost:9876/_karma_webpack_/inline.bundle.js:55:30)\n    at webpackContext (http://localhost:9876/_karma_webpack_/main.bundle.js:11:9)\n    at Array.map (<anonymous>)\n    at Object.../../../../../src/test.ts (http://localhost:9876/_karma_webpack_/main.bundle.js:385:16)"
  }
`

**Comment by Mokkapps** [comment] 2018-02-12 20:36
I fixed it this way:

First I moved all electron dependent code in the ElectronService, like showing dialogs or opening shell.

Changed imports to
`import { ipcRenderer } from 'electron';`

all other electron related properties like "remote" and "shell" are accessed via "this.electron" which is set this way:

```
@Injectable()
export class ElectronService {
  ipcRenderer: typeof ipcRenderer;
  childProcess: typeof childProcess;
  electron: any;

  constructor(private translateService: TranslateService) {
    // Conditional imports
    if (this.isElectron()) {
      this.electron = window.require('electron');
      this.ipcRenderer = this.electron.ipcRenderer;
      this.childProcess = window.require('child_process');
    }
```

**Closed** 2018-04-15 10:35 UTC
